features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: 'https://www.facebook.com/'
twitter_url: 'https://twitter.com/'
google_plus_url: 'https://plus.google.com/'
linkedin_url: 'http://www.linkedin.com/'
pinterest_url: 'https://www.pinterest.com/'
rss_url: rss.xml
copyright_text: 'Copyright 2017· All rights reserved'
show_social_icon: 1
show_credit_link: 1
_core:
  default_config_hash: FIKpUAUBhRvu30trYoPz9z7O8dAeWlZ3GILxKamftng
langcode: es
logo:
  use_default: 0
  path: 'public://logo-bizart.png'
favicon:
  use_default: 1
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
